version: '3'
services:
  vector_color:
    image: developmentseed/vector_color:v1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/mnt/data
    env_file:
      - ./.env